# .goreleaser.yaml
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  github:
    owner: your-github-username
    name: your-repo-name
  draft: false
  prerelease: auto
  mode: append
  make_latest: true
  name_template: "Release {{.Tag}}"
  header: |
    ## Release {{.Tag}} ({{ .Date }})

    Welcome to this new release!

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"
# Uncomment and modify the following sections as needed

# dockers:
#   - image_templates:
#     - "your-dockerhub-username/your-image:{{ .Tag }}"
#     - "your-dockerhub-username/your-image:v{{ .Major }}"
#     - "your-dockerhub-username/your-image:v{{ .Major }}.{{ .Minor }}"
#     - "your-dockerhub-username/your-image:latest"

# brews:
#   - name: your-app
#     tap:
#       owner: your-github-username
#       name: homebrew-tap
#     folder: Formula
#     homepage: "https://example.com/your-app"
#     description: "Description of your application"
#     license: "MIT"

# signs:
#   - artifacts: checksum

# nfpms:
#   - maintainer: Your Name <your@email.com>
#     description: Software package description
#     homepage: https://example.com/your-app
#     license: MIT
#     formats:
#       - deb
#       - rpm

# publishers:
#   - name: fury.io
#     ids:
#       - nfpm

# before:
#   hooks:
#     - go mod tidy
#     - go generate ./...

# after:
#   hooks:
#     - ./scripts/post-release.sh

# dist: dist
